name: .NET

on:
  push:
    tags: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set Context
      run: cd /src
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack -c Release -o ./nupkgs -p:PackageVersion=${{ github.ref_name }}
    - name: Nuget
      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json
